// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: languages.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (
    name,
    version,
    source_file,
    compile_command,
    run_command
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, version, source_file, compile_command, run_command, is_archived, created_at, updated_at
`

type CreateLanguageParams struct {
	Name           string      `db:"name" json:"name"`
	Version        string      `db:"version" json:"version"`
	SourceFile     string      `db:"source_file" json:"source_file"`
	CompileCommand pgtype.Text `db:"compile_command" json:"compile_command"`
	RunCommand     string      `db:"run_command" json:"run_command"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage,
		arg.Name,
		arg.Version,
		arg.SourceFile,
		arg.CompileCommand,
		arg.RunCommand,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SourceFile,
		&i.CompileCommand,
		&i.RunCommand,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByID = `-- name: GetLanguageByID :one
SELECT id, name, version, source_file, compile_command, run_command FROM languages
WHERE id = $1
LIMIT 1
`

type GetLanguageByIDRow struct {
	ID             int64       `db:"id" json:"id"`
	Name           string      `db:"name" json:"name"`
	Version        string      `db:"version" json:"version"`
	SourceFile     string      `db:"source_file" json:"source_file"`
	CompileCommand pgtype.Text `db:"compile_command" json:"compile_command"`
	RunCommand     string      `db:"run_command" json:"run_command"`
}

func (q *Queries) GetLanguageByID(ctx context.Context, id int64) (GetLanguageByIDRow, error) {
	row := q.db.QueryRow(ctx, getLanguageByID, id)
	var i GetLanguageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SourceFile,
		&i.CompileCommand,
		&i.RunCommand,
	)
	return i, err
}

const getPublicLanguageByID = `-- name: GetPublicLanguageByID :one
SELECT id, name, version, is_archived
FROM languages
WHERE id = $1
LIMIT 1
`

type GetPublicLanguageByIDRow struct {
	ID         int64  `db:"id" json:"id"`
	Name       string `db:"name" json:"name"`
	Version    string `db:"version" json:"version"`
	IsArchived bool   `db:"is_archived" json:"is_archived"`
}

func (q *Queries) GetPublicLanguageByID(ctx context.Context, id int64) (GetPublicLanguageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicLanguageByID, id)
	var i GetPublicLanguageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.IsArchived,
	)
	return i, err
}

const listActiveLanguages = `-- name: ListActiveLanguages :many
SELECT id, name, version, source_file, compile_command, run_command FROM languages
WHERE is_archived = FALSE
ORDER BY id
`

type ListActiveLanguagesRow struct {
	ID             int64       `db:"id" json:"id"`
	Name           string      `db:"name" json:"name"`
	Version        string      `db:"version" json:"version"`
	SourceFile     string      `db:"source_file" json:"source_file"`
	CompileCommand pgtype.Text `db:"compile_command" json:"compile_command"`
	RunCommand     string      `db:"run_command" json:"run_command"`
}

func (q *Queries) ListActiveLanguages(ctx context.Context) ([]ListActiveLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listActiveLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLanguagesRow
	for rows.Next() {
		var i ListActiveLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.SourceFile,
			&i.CompileCommand,
			&i.RunCommand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, name, version, source_file, compile_command, run_command FROM languages
ORDER BY id
`

type ListLanguagesRow struct {
	ID             int64       `db:"id" json:"id"`
	Name           string      `db:"name" json:"name"`
	Version        string      `db:"version" json:"version"`
	SourceFile     string      `db:"source_file" json:"source_file"`
	CompileCommand pgtype.Text `db:"compile_command" json:"compile_command"`
	RunCommand     string      `db:"run_command" json:"run_command"`
}

func (q *Queries) ListLanguages(ctx context.Context) ([]ListLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguagesRow
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.SourceFile,
			&i.CompileCommand,
			&i.RunCommand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLanguages = `-- name: ListPublicLanguages :many
SELECT id, name, version, is_archived
FROM languages
ORDER BY name
`

type ListPublicLanguagesRow struct {
	ID         int64  `db:"id" json:"id"`
	Name       string `db:"name" json:"name"`
	Version    string `db:"version" json:"version"`
	IsArchived bool   `db:"is_archived" json:"is_archived"`
}

func (q *Queries) ListPublicLanguages(ctx context.Context) ([]ListPublicLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listPublicLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicLanguagesRow
	for rows.Next() {
		var i ListPublicLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
