// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID             int64              `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Version        string             `db:"version" json:"version"`
	SourceFile     string             `db:"source_file" json:"source_file"`
	CompileCommand pgtype.Text        `db:"compile_command" json:"compile_command"`
	RunCommand     string             `db:"run_command" json:"run_command"`
	IsArchived     bool               `db:"is_archived" json:"is_archived"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Submission struct {
	ID                                   int64              `db:"id" json:"id"`
	LanguageID                           int64              `db:"language_id" json:"language_id"`
	SourceCode                           string             `db:"source_code" json:"source_code"`
	Status                               string             `db:"status" json:"status"`
	CompileOutput                        pgtype.Text        `db:"compile_output" json:"compile_output"`
	Message                              pgtype.Text        `db:"message" json:"message"`
	InternalError                        pgtype.Text        `db:"internal_error" json:"internal_error"`
	CpuTimeLimit                         float64            `db:"cpu_time_limit" json:"cpu_time_limit"`
	CpuExtraTime                         float64            `db:"cpu_extra_time" json:"cpu_extra_time"`
	WallTimeLimit                        float64            `db:"wall_time_limit" json:"wall_time_limit"`
	MemoryLimit                          int32              `db:"memory_limit" json:"memory_limit"`
	StackLimit                           int32              `db:"stack_limit" json:"stack_limit"`
	MaxProcessesAndOrThreads             int32              `db:"max_processes_and_or_threads" json:"max_processes_and_or_threads"`
	EnablePerProcessAndThreadTimeLimit   bool               `db:"enable_per_process_and_thread_time_limit" json:"enable_per_process_and_thread_time_limit"`
	EnablePerProcessAndThreadMemoryLimit bool               `db:"enable_per_process_and_thread_memory_limit" json:"enable_per_process_and_thread_memory_limit"`
	MaxFileSize                          int32              `db:"max_file_size" json:"max_file_size"`
	NumberOfRuns                         int32              `db:"number_of_runs" json:"number_of_runs"`
	RedirectStderrToStdout               bool               `db:"redirect_stderr_to_stdout" json:"redirect_stderr_to_stdout"`
	EnableNetwork                        bool               `db:"enable_network" json:"enable_network"`
	Time                                 pgtype.Float8      `db:"time" json:"time"`
	WallTime                             pgtype.Float8      `db:"wall_time" json:"wall_time"`
	Memory                               pgtype.Int4        `db:"memory" json:"memory"`
	StartedAt                            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt                           pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt                            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Mode                                 string             `db:"mode" json:"mode"`
}

type TestCaseResult struct {
	ID             int64              `db:"id" json:"id"`
	SubmissionID   int64              `db:"submission_id" json:"submission_id"`
	Position       int16              `db:"position" json:"position"`
	Stdin          pgtype.Text        `db:"stdin" json:"stdin"`
	ExpectedOutput pgtype.Text        `db:"expected_output" json:"expected_output"`
	Stdout         pgtype.Text        `db:"stdout" json:"stdout"`
	Stderr         pgtype.Text        `db:"stderr" json:"stderr"`
	ExitCode       pgtype.Int4        `db:"exit_code" json:"exit_code"`
	ExitSignal     pgtype.Int4        `db:"exit_signal" json:"exit_signal"`
	Status         string             `db:"status" json:"status"`
	Time           pgtype.Float8      `db:"time" json:"time"`
	WallTime       pgtype.Float8      `db:"wall_time" json:"wall_time"`
	Memory         pgtype.Int4        `db:"memory" json:"memory"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
