// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSubmission = `-- name: CompleteSubmission :one
UPDATE submissions
SET
    status = $2,
    compile_output = $3,
    stdout = $4,
    stderr = $5,
    message = $6,
    internal_error = $7,
    exit_code = $8,
    exit_signal = $9,
    time = $10,
    wall_time = $11,
    memory = $12,
    started_at = $13,
    finished_at = $14,
    updated_at = NOW()
WHERE id = $1
RETURNING id, language_id, source_code, stdin, status, compile_output, stdout, stderr, message, internal_error, exit_code, exit_signal, cpu_time_limit, cpu_extra_time, wall_time_limit, memory_limit, stack_limit, max_processes_and_or_threads, enable_per_process_and_thread_time_limit, enable_per_process_and_thread_memory_limit, max_file_size, number_of_runs, redirect_stderr_to_stdout, enable_network, time, wall_time, memory, started_at, finished_at, created_at, updated_at
`

type CompleteSubmissionParams struct {
	ID            int64              `db:"id" json:"id"`
	Status        string             `db:"status" json:"status"`
	CompileOutput pgtype.Text        `db:"compile_output" json:"compile_output"`
	Stdout        pgtype.Text        `db:"stdout" json:"stdout"`
	Stderr        pgtype.Text        `db:"stderr" json:"stderr"`
	Message       pgtype.Text        `db:"message" json:"message"`
	InternalError pgtype.Text        `db:"internal_error" json:"internal_error"`
	ExitCode      pgtype.Int4        `db:"exit_code" json:"exit_code"`
	ExitSignal    pgtype.Int4        `db:"exit_signal" json:"exit_signal"`
	Time          pgtype.Float8      `db:"time" json:"time"`
	WallTime      pgtype.Float8      `db:"wall_time" json:"wall_time"`
	Memory        pgtype.Int4        `db:"memory" json:"memory"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt    pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

func (q *Queries) CompleteSubmission(ctx context.Context, arg CompleteSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, completeSubmission,
		arg.ID,
		arg.Status,
		arg.CompileOutput,
		arg.Stdout,
		arg.Stderr,
		arg.Message,
		arg.InternalError,
		arg.ExitCode,
		arg.ExitSignal,
		arg.Time,
		arg.WallTime,
		arg.Memory,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Stdin,
		&i.Status,
		&i.CompileOutput,
		&i.Stdout,
		&i.Stderr,
		&i.Message,
		&i.InternalError,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CpuTimeLimit,
		&i.CpuExtraTime,
		&i.WallTimeLimit,
		&i.MemoryLimit,
		&i.StackLimit,
		&i.MaxProcessesAndOrThreads,
		&i.EnablePerProcessAndThreadTimeLimit,
		&i.EnablePerProcessAndThreadMemoryLimit,
		&i.MaxFileSize,
		&i.NumberOfRuns,
		&i.RedirectStderrToStdout,
		&i.EnableNetwork,
		&i.Time,
		&i.WallTime,
		&i.Memory,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    language_id,
    source_code,
    stdin,
    cpu_time_limit,
    cpu_extra_time,
    wall_time_limit,
    memory_limit,
    stack_limit,
    max_processes_and_or_threads,
    enable_per_process_and_thread_time_limit,
    enable_per_process_and_thread_memory_limit,
    max_file_size,
    redirect_stderr_to_stdout,
    enable_network
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14
)
RETURNING id, language_id, source_code, stdin, status, compile_output, stdout, stderr, message, internal_error, exit_code, exit_signal, cpu_time_limit, cpu_extra_time, wall_time_limit, memory_limit, stack_limit, max_processes_and_or_threads, enable_per_process_and_thread_time_limit, enable_per_process_and_thread_memory_limit, max_file_size, number_of_runs, redirect_stderr_to_stdout, enable_network, time, wall_time, memory, started_at, finished_at, created_at, updated_at
`

type CreateSubmissionParams struct {
	LanguageID                           int64       `db:"language_id" json:"language_id"`
	SourceCode                           string      `db:"source_code" json:"source_code"`
	Stdin                                pgtype.Text `db:"stdin" json:"stdin"`
	CpuTimeLimit                         float64     `db:"cpu_time_limit" json:"cpu_time_limit"`
	CpuExtraTime                         float64     `db:"cpu_extra_time" json:"cpu_extra_time"`
	WallTimeLimit                        float64     `db:"wall_time_limit" json:"wall_time_limit"`
	MemoryLimit                          int32       `db:"memory_limit" json:"memory_limit"`
	StackLimit                           int32       `db:"stack_limit" json:"stack_limit"`
	MaxProcessesAndOrThreads             int32       `db:"max_processes_and_or_threads" json:"max_processes_and_or_threads"`
	EnablePerProcessAndThreadTimeLimit   bool        `db:"enable_per_process_and_thread_time_limit" json:"enable_per_process_and_thread_time_limit"`
	EnablePerProcessAndThreadMemoryLimit bool        `db:"enable_per_process_and_thread_memory_limit" json:"enable_per_process_and_thread_memory_limit"`
	MaxFileSize                          int32       `db:"max_file_size" json:"max_file_size"`
	RedirectStderrToStdout               bool        `db:"redirect_stderr_to_stdout" json:"redirect_stderr_to_stdout"`
	EnableNetwork                        bool        `db:"enable_network" json:"enable_network"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.LanguageID,
		arg.SourceCode,
		arg.Stdin,
		arg.CpuTimeLimit,
		arg.CpuExtraTime,
		arg.WallTimeLimit,
		arg.MemoryLimit,
		arg.StackLimit,
		arg.MaxProcessesAndOrThreads,
		arg.EnablePerProcessAndThreadTimeLimit,
		arg.EnablePerProcessAndThreadMemoryLimit,
		arg.MaxFileSize,
		arg.RedirectStderrToStdout,
		arg.EnableNetwork,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Stdin,
		&i.Status,
		&i.CompileOutput,
		&i.Stdout,
		&i.Stderr,
		&i.Message,
		&i.InternalError,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CpuTimeLimit,
		&i.CpuExtraTime,
		&i.WallTimeLimit,
		&i.MemoryLimit,
		&i.StackLimit,
		&i.MaxProcessesAndOrThreads,
		&i.EnablePerProcessAndThreadTimeLimit,
		&i.EnablePerProcessAndThreadMemoryLimit,
		&i.MaxFileSize,
		&i.NumberOfRuns,
		&i.RedirectStderrToStdout,
		&i.EnableNetwork,
		&i.Time,
		&i.WallTime,
		&i.Memory,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, language_id, source_code, stdin, status, compile_output, stdout, stderr, message, internal_error, exit_code, exit_signal, cpu_time_limit, cpu_extra_time, wall_time_limit, memory_limit, stack_limit, max_processes_and_or_threads, enable_per_process_and_thread_time_limit, enable_per_process_and_thread_memory_limit, max_file_size, number_of_runs, redirect_stderr_to_stdout, enable_network, time, wall_time, memory, started_at, finished_at, created_at, updated_at FROM submissions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Stdin,
		&i.Status,
		&i.CompileOutput,
		&i.Stdout,
		&i.Stderr,
		&i.Message,
		&i.InternalError,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CpuTimeLimit,
		&i.CpuExtraTime,
		&i.WallTimeLimit,
		&i.MemoryLimit,
		&i.StackLimit,
		&i.MaxProcessesAndOrThreads,
		&i.EnablePerProcessAndThreadTimeLimit,
		&i.EnablePerProcessAndThreadMemoryLimit,
		&i.MaxFileSize,
		&i.NumberOfRuns,
		&i.RedirectStderrToStdout,
		&i.EnableNetwork,
		&i.Time,
		&i.WallTime,
		&i.Memory,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, language_id, source_code, stdin, status, compile_output, stdout, stderr, message, internal_error, exit_code, exit_signal, cpu_time_limit, cpu_extra_time, wall_time_limit, memory_limit, stack_limit, max_processes_and_or_threads, enable_per_process_and_thread_time_limit, enable_per_process_and_thread_memory_limit, max_file_size, number_of_runs, redirect_stderr_to_stdout, enable_network, time, wall_time, memory, started_at, finished_at, created_at, updated_at FROM submissions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubmissionsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.SourceCode,
			&i.Stdin,
			&i.Status,
			&i.CompileOutput,
			&i.Stdout,
			&i.Stderr,
			&i.Message,
			&i.InternalError,
			&i.ExitCode,
			&i.ExitSignal,
			&i.CpuTimeLimit,
			&i.CpuExtraTime,
			&i.WallTimeLimit,
			&i.MemoryLimit,
			&i.StackLimit,
			&i.MaxProcessesAndOrThreads,
			&i.EnablePerProcessAndThreadTimeLimit,
			&i.EnablePerProcessAndThreadMemoryLimit,
			&i.MaxFileSize,
			&i.NumberOfRuns,
			&i.RedirectStderrToStdout,
			&i.EnableNetwork,
			&i.Time,
			&i.WallTime,
			&i.Memory,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :exec
UPDATE submissions
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSubmissionStatusParams struct {
	ID     int64  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionStatus, arg.ID, arg.Status)
	return err
}
