ALTER TABLE submissions
    ADD COLUMN IF NOT EXISTS stdin TEXT,
    ADD COLUMN IF NOT EXISTS stdout TEXT,
    ADD COLUMN IF NOT EXISTS stderr TEXT,
    ADD COLUMN IF NOT EXISTS exit_code INTEGER,
    ADD COLUMN IF NOT EXISTS exit_signal INTEGER;
